import argparse
import glob
import json
import os
import sys
import cv2
import numpy as np


def parse_arguments():
    """
    Parses CLI arguments for extrinsic PnP calibration.
    """
    parser = argparse.ArgumentParser(
        description="Compute camera extrinsic matrices [R | t] relative to tatami world frame."
    )
    parser.add_argument(
        "--intrinsic_json", "-i", type=str, required=True,
        help="Path to camera intrinsic parameters JSON."
    )
    parser.add_argument(
        "--mat_corners_json", "-c", type=str, required=True,
        help="Path to mat_corners.json generated by AnnotateMatCorners.py."
    )
    parser.add_argument(
        "--camera_id", type=str, required=True,
        help="Identifier matching entry in mat_corners.json (e.g. gopro_0, realsense_cam_0)."
    )
    parser.add_argument(
        "--board_dir", "-b", type=str, default=None,
        help="Optional path to directory containing vertical ChArUco position subfolders."
    )
    parser.add_argument(
        "--output_json", "-o", type=str, default="extrinsics.json",
        help="Output path for computed extrinsic calibration JSON."
    )
    parser.add_argument(
        "--squares_x", type=int, default=5,
        help="Number of chessboard squares along X dimension."
    )
    parser.add_argument(
        "--squares_y", type=int, default=7,
        help="Number of chessboard squares along Y dimension."
    )
    parser.add_argument(
        "--square_len", type=float, default=0.04,
        help="Physical square side length in meters (update to 0.08 if using 80mm board)."
    )
    parser.add_argument(
        "--marker_len", type=float, default=0.03,
        help="Physical ArUco marker side length in meters (update to 0.06 if using 80mm board)."
    )
    parser.add_argument(
        "--max_rmse", type=float, default=1.5,
        help="Maximum permissible reprojection RMSE in pixels."
    )
    return parser.parse_args()


def load_intrinsics(json_path):
    """
    Ingests intrinsic parameters supporting both RealSense and GoPro output formats.
    
    Arguments:
        json_path (str): Path to intrinsic parameters JSON.

    Returns:
        tuple: (K, D, model, width, height)
    """
    with open(json_path, 'r') as f:
        data = json.load(f)

    model = data.get("camera_model", "standard").lower()
    width = int(data["width"])
    height = int(data["height"])

    if "camera_matrix" in data:
        K = np.array(data["camera_matrix"], dtype=np.float64)
        D = np.array(data["distortion_coefficients"], dtype=np.float64).reshape(-1, 1)
    else:
        fx, fy = data["fx"], data["fy"]
        cx, cy = data["cx"], data["cy"]
        K = np.array([[fx, 0.0, cx], [0.0, fy, cy], [0.0, 0.0, 1.0]], dtype=np.float64)
        D = np.array(data["distortion_coeffs"], dtype=np.float64).reshape(-1, 1)

    return K, D, model, width, height


def undistort_points_to_normalized(pts_2d, K, D, model):
    """
    Undistorts pixel coordinates directly into ideal normalized pinhole image coordinates.
    
    Arguments:
        pts_2d (np.ndarray): (N, 2) pixel coordinates.
        K (np.ndarray): 3x3 intrinsic matrix.
        D (np.ndarray): Distortion vector.
        model (str): Distortion model ('fisheye', 'rational', or 'standard').

    Returns:
        np.ndarray: (N, 1, 2) undistorted coordinates in normalized camera plane.
    """
    pts_in = pts_2d.reshape(-1, 1, 2).astype(np.float64)
    if model == "fisheye":
        # Returns normalized ray coordinates (x, y) where z=1
        undist_norm = cv2.fisheye.undistortPoints(pts_in, K, D)
    else:
        undist_norm = cv2.undistortPoints(pts_in, K, D)
    return undist_norm


def build_board_world_coords(base_xy, facing, squares_x, squares_y, square_len):
    """
    Computes 3D coordinates for all inner ChArUco corners on a vertical board flush to mat floor.
    
    Arguments:
        base_xy (tuple): (X, Y) world position of bottom-left corner of the board base.
        facing (str): 'facing_x', 'facing_y', or 'diagonal'.
        squares_x (int): Horizontal squares count.
        squares_y (int): Vertical squares count.
        square_len (float): Physical square length in meters.

    Returns:
        np.ndarray: (N, 3) 3D world coordinates.
    """
    bx, by = base_xy
    inner_cols = squares_x - 1
    inner_rows = squares_y - 1
    cos45 = np.cos(np.radians(45))
    sin45 = np.sin(np.radians(45))

    coords = []
    # Row 0 = top = highest Z in world coordinates
    for row in range(inner_rows):
        z = (inner_rows - 1 - row) * square_len
        for col in range(inner_cols):
            if facing == 'facing_x':
                wx = bx + col * square_len
                wy = by
            elif facing == 'facing_y':
                wx = bx
                wy = by + col * square_len
            else:  # diagonal
                wx = bx + col * square_len * cos45
                wy = by + col * square_len * sin45
            coords.append([wx, wy, z])

    return np.array(coords, dtype=np.float32)


def extract_vertical_board_correspondences(board_dir, corner_world_xy, K, D, model, squares_x, squares_y, square_len, marker_len):
    """
    Scans position subfolders, detects ChArUco corners, and computes undistorted normalized ray coordinates.
    """
    dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
    board = cv2.aruco.CharucoBoard((squares_x, squares_y), square_len, marker_len, dictionary)
    detector = cv2.aruco.CharucoDetector(board)

    rotations = ['facing_x', 'facing_y', 'diagonal']
    all_norm_pts = []
    all_world_pts = []

    pos_mapping = {**corner_world_xy, 'centre': (0.0, 0.0)}

    for pos_name, base_xy in pos_mapping.items():
        for facing in rotations:
            subfolder = os.path.join(board_dir, f"{pos_name}_{facing}")
            if not os.path.isdir(subfolder):
                continue

            img_paths = glob.glob(os.path.join(subfolder, "*.jpg")) + glob.glob(os.path.join(subfolder, "*.png"))
            if not img_paths:
                continue

            board_world = build_board_world_coords(base_xy, facing, squares_x, squares_y, square_len)

            for ipath in img_paths:
                img = cv2.imread(ipath)
                if img is None:
                    continue
                gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                charuco_corners, charuco_ids, _, _ = detector.detectBoard(gray)

                if charuco_corners is not None and charuco_ids is not None and len(charuco_corners) >= 6:
                    ids_flat = charuco_ids.flatten()
                    max_id = (squares_x - 1) * (squares_y - 1) - 1
                    valid_mask = ids_flat <= max_id

                    if not np.any(valid_mask):
                        continue

                    valid_corners = charuco_corners[valid_mask].reshape(-1, 2)
                    valid_world = board_world[ids_flat[valid_mask]]

                    # Undistort corners directly into normalized camera rays
                    norm_pts = undistort_points_to_normalized(valid_corners, K, D, model)

                    all_norm_pts.append(norm_pts)
                    all_world_pts.append(valid_world.reshape(-1, 1, 3))

    if not all_norm_pts:
        return None, None

    return np.concatenate(all_norm_pts, axis=0), np.concatenate(all_world_pts, axis=0)


def main():
    args = parse_arguments()

    print("=" * 60)
    print(f" MULTI-CAMERA EXTRINSIC SOLVER (HPC BATCH)")
    print(f" Camera ID       : {args.camera_id}")
    print(f" Intrinsics File : {args.intrinsic_json}")
    print("=" * 60)

    # 1. Ingest intrinsics
    K, D, model, w, h = load_intrinsics(args.intrinsic_json)

    # 2. Ingest tatami corner annotations
    with open(args.mat_corners_json, 'r') as f:
        corners_meta = json.load(f)

    if args.camera_id not in corners_meta["cameras"]:
        raise KeyError(f"[-] Camera ID '{args.camera_id}' not found in {args.mat_corners_json}")

    cam_annot = corners_meta["cameras"][args.camera_id]["corners_2d"]
    world_meta = corners_meta["metadata"]["world_points"]

    order = ["top_left", "top_right", "bottom_right", "bottom_left"]
    mat_2d = np.array([cam_annot[k] for k in order], dtype=np.float32)
    mat_3d = np.array([world_meta[k] for k in order], dtype=np.float32)

    # Undistort clicked mat corners to normalized camera coordinates
    mat_norm_pts = undistort_points_to_normalized(mat_2d, K, D, model)
    mat_world_pts = mat_3d.reshape(-1, 1, 3)

    combined_norm_pts = mat_norm_pts
    combined_world_pts = mat_world_pts

    # 3. Optional: Integrate vertical ChArUco 3D point cloud correspondences
    if args.board_dir and os.path.isdir(args.board_dir):
        print(f"[+] Ingesting vertical ChArUco dataset from: {args.board_dir}")
        corner_world_xy = {k: (world_meta[k][0], world_meta[k][1]) for k in order}
        b_norm, b_world = extract_vertical_board_correspondences(
            args.board_dir, corner_world_xy, K, D, model,
            args.squares_x, args.squares_y, args.square_len, args.marker_len
        )
        if b_norm is not None:
            combined_norm_pts = np.concatenate([mat_norm_pts, b_norm], axis=0)
            combined_world_pts = np.concatenate([mat_world_pts, b_world], axis=0)
            print(f"    Added {len(b_norm)} vertical target correspondences.")

    print(f"[+] Total geometric constraints: {len(combined_world_pts)} points")

    # 4. Execute SolvePnP in normalized coordinates (K = Identity, zero distortion)
    # Using normalized rays decouples solvePnP from the camera model specifics
    eye_k = np.eye(3, dtype=np.float64)
    zero_dist = np.zeros((4, 1), dtype=np.float64)

    success, rvec, tvec = cv2.solvePnP(
        combined_world_pts,
        combined_norm_pts,
        eye_k,
        zero_dist,
        flags=cv2.SOLVEPNP_ITERATIVE
    )

    if not success:
        raise RuntimeError("[-] cv2.solvePnP convergence failed.")

    # 5. Measure Reprojection Residuals in Pixels
    R, _ = cv2.Rodrigues(rvec)

    if model == "fisheye":
        proj_2d, _ = cv2.fisheye.projectPoints(
            combined_world_pts.reshape(-1, 1, 3).astype(np.float64),
            rvec.astype(np.float64),
            tvec.astype(np.float64),
            K.astype(np.float64),
            D.astype(np.float64)
        )
    else:
        proj_2d, _ = cv2.projectPoints(combined_world_pts, rvec, tvec, K, D)

    # Project the original unwarped pixels (for tatami corners) to evaluate real RMSE
    diff = proj_2d.reshape(-1, 2)[:4] - mat_2d
    rmse_px = float(np.sqrt(np.mean(np.sum(diff ** 2, axis=1))))

    print(f"[+] Optimization Converged. Reprojection RMSE on mat corners: {rmse_px:.3f} px")

    if rmse_px > args.max_rmse:
        raise ValueError(f"[-] Reprojection error ({rmse_px:.3f} px) exceeds cutoff ({args.max_rmse} px). Check annotations.")

    # Camera optical center in world coordinates: C = -R^T * t
    cam_pos_world = (-R.T @ tvec).flatten()
    rt_matrix = np.hstack((R, tvec))
    proj_matrix = K @ rt_matrix

    payload = {
        "camera_id": args.camera_id,
        "camera_model": model,
        "rotation_matrix": R.tolist(),
        "translation_vector": tvec.flatten().tolist(),
        "projection_matrix": proj_matrix.tolist(),
        "camera_position_world": cam_pos_world.tolist(),
        "reprojection_rmse_px": round(rmse_px, 4),
        "correspondences_evaluated": int(len(combined_world_pts))
    }

    os.makedirs(os.path.dirname(os.path.abspath(args.output_json)), exist_ok=True)
    with open(args.output_json, 'w') as f:
        json.dump(payload, f, indent=4)

    print(f"[+] Extrinsics successfully written to: {args.output_json}")
    print(f"    World Position: X={cam_pos_world[0]:.2f}m, Y={cam_pos_world[1]:.2f}m, Z={cam_pos_world[2]:.2f}m (Elevation)")


if __name__ == "__main__":
    main()